name: TreasureChest
main: awzaw\treasurechest\Main
version: 1.2.3
author: Awzaw
api: [3.0.0]
load: POSTWORLD
commands:
 tchest:
  permission: tchest
  description: Add a new treasure chest
  aliases: ["tc"]
  usage: /tchest
permissions:
   tchest:
    default: op
