name: TreasureChest
main: awzaw\treasurechest\Main
version: 1.1
author: Awzaw
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3]
load: POSTWORLD
commands:
 tchest:
  permission: tchest
  description: Add a new treasure chest
  aliases: ["tc"]
  usage: /tchest
permissions:
   tchest:
    default: op
