name: TreasureChest
main: awzaw\treasurechest\Main
version: 1.2.2
author: Awzaw
api: [3.0.0]
load: POSTWORLD
commands:
 tchest:
  permission: tchest
  description: Add a new treasure chest
  usage: /tchest
permissions:
   tchest:
    default: op